first_post
inf380p/inf380p.github.io pull request #401
Opened 2022-12-01 20:41 UTC by manasvini2906

…t-manasvini2906.md

2022-12-02 03:37 UTC, shashwatj14 requested changes
To keep things simple, change the author name in the title from manasvini2906 to just Manasvini.

2022-12-02 03:39 UTC, shashwatj14 commented on _posts/manasvini2906/2022-09-22-First-post-manasvini2906.md
> +title : 'manasvini2906's first post!'
title: 'Manasvini's first post!'

2022-12-06 01:58 UTC, atUtexas approved these changes
Making this change will definitely help your post appear in the people's section of our class website. If it still doesn't work, consider using parenthesis"" for the title.

2022-12-06 01:59 UTC, atUtexas commented
Making this change will definitely help your post appear in the people's section of our class website. If it still doesn't work, consider using parenthesis"" for the title.

2022-12-11 23:12 UTC, merged