Created April's Focused Reflection
inf380p/inf380p.github.io pull request #68
Opened 2022-09-29 02:27 UTC by alm7468

This is my focused reflection on a bit of code that operates like an order taker at a fast food restaurant.
I jumped the gun and navigated to the next phase of the pull request without including my metadata bit at the top. I will add it.

2022-09-29 19:31 UTC, alm7468 commented on _posts/alm7468/2022-09-28-Focused-Reflection-alm7468.md
> +title: April's Focused Reflection
Put quotes " " around the title please. 
Should read "April's Focused Reflection"

2022-11-03 19:29 UTC, haley-triem reviewed
Looking really good! I like how conversational it is--makes it easy to read and relate to ... My only suggestion is to maybe add spaces in between each line for code lines 16-19, because it's a chunk   of text visually and might be easier for people to read :)

2022-11-03 19:48 UTC, haley-triem requested changes
Looking really good! I like how conversational it is--makes it easy to read and relate to ... My only suggestion is to maybe add spaces in between each line for code lines 16-19, because it's a chunk of text visually and might be easier for people to read :)

2022-11-03 19:58 UTC, haley-triem approved these changes

2022-11-03 19:58 UTC, merged